# Диплом

In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
encoded_scaled_df = pd.read_csv('encoded_scaled_df.csv')

In [3]:
encoded_scaled_df

,Unnamed: 0.1,Unnamed: 0,Ship Mode,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Price,...,ship_year,ship_month,ship_day,ship_dayofweek,ship_quarter,ship_dayofyear,ship_weekofyear,ship_hour,ship_minute,ship_second
0,0,234,0,2.990438,-0.642117,-0.673429,1.006289,8.953183,0,5.879120,...,2012,4,1,6,2,92,13,0,0,0
1,1,238,0,3.874441,1.581116,-0.673429,3.384700,8.895208,1,1.642543,...,2014,12,26,4,4,360,52,0,0,0
2,2,239,1,6.165302,1.136470,0.269444,1.612463,8.880952,1,3.422364,...,2014,7,4,4,3,185,27,0,0,0
3,3,240,0,2.948701,-0.197470,-0.673429,2.642943,8.825115,0,3.636833,...,2014,11,23,6,4,327,47,0,0,0
4,4,241,3,5.209868,0.247177,-0.673429,8.048805,8.802543,1,4.611799,...,2013,1,27,6,1,27,4,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50805,50805,51285,1,-0.436886,0.691823,-0.673429,-0.178292,-0.549711,3,-0.561471,...,2014,6,19,3,2,170,25,0,0,0
50806,50806,51286,3,-0.620085,-1.086763,3.098064,-0.227278,-0.549711,3,-0.691205,...,2014,6,24,1,2,175,26,0,0,0
50807,50807,51287,1,-0.556400,-0.197470,-0.673429,-0.119519,-0.549711,1,-0.616971,...,2013,12,2,0,4,336,49,0,0,0
50808,50808,51288,3,-0.583261,-0.642117,-0.673429,-0.196629,-0.549948,3,-0.626462,...,2012,2,22,2,1,53,8,0,0,0
50809,50809,51289,2,-0.447426,-0.197470,-0.673429,-0.201868,-0.549948,1,-0.484720,...,2012,5,26,5,2,147,21,0,0,0

# Linear Regression

In [6]:
X = encoded_scaled_df.drop(columns=["Price"])
y = encoded_scaled_df["Price"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [8]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R² Score: {r2}")

MAE: 1447.3921097284872
MSE: 2474297854.718406
RMSE: 49742.31452916527
R² Score: -2437769420.4925027

/Users/ilabarymov/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [16]:
ridge = Ridge().fit(X_train, y_train)
y_pred = ridge.predict(X_test)
print('R2:', r2_score(y_test, y_pred))

R2: 0.7798808670698469